# Default AWS Config
version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(module)s:%(funcName)s:%(lineno)s - %(message)s"
  plaintext:
    format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(module)s:%(funcName)s:%(lineno)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: plaintext
    level: DEBUG
    stream: ext://sys.stdout
  watchtower:
    class: watchtower.CloudWatchLogHandler
    # boto3_profile_name: workers
    formatter: json
    level: DEBUG
    log_group: /aws/ec2/watchtower_workers_ec2instance_py
    stream_name: "{logger_name}-{strftime:%y-%m-%d}"
    send_interval: 10
    create_log_group: False
root:
  level: DEBUG
  propagate: True
  handlers: [console, watchtower]
loggers:
  botocore:
    level: INFO
    propagate: False
  urllib3:
    level: INFO
    propagate: False
  boto3:
    level: INFO
    propagate: False
  s3transfer:
    level: INFO
    propagate: False
